### ISSUE TITLE
frontend: landing page

### ISSUE THREAD

**Issue by chinathaip** [stamford-syntax-club/style-war#1]
### Tasks 
- [x] @chinathaip integrate Clerk JS
- [x] use https://clerk.com/docs/components/authentication/sign-in as a sign-in form
      - after a successful login, it should redirect to the editor page.
- [x] create a "practice" button that redirect to a practice page
- [x] feel free to style it however you like

![image](https://github.com/stamford-syntax-club/style-war/assets/92321280/75a9e810-437f-44d3-b0cb-dc854cc6d617)
